### ISSUE TITLE
Illegal instruction with rep prefix on Skylake

### ISSUE THREAD

**Issue by falk-hueffner** [StanfordPL/stoke#840]
I'm now trying on a i7-6700K (Skylake) running Fedora (I had to build gcc-4.9 and cln myself since Fedora has a too new g++). I'm quickly getting something like:

```
Progress Update: 

Lowest Cost Discovered (2)     Lowest Known Correct Cost (2)     

._Z6popcntm:                   ._Z6popcntm:                      
popcntl %edi, %eax             popcntl %edi, %eax                
cmovaq %rax, %rax              cmovaq %rax, %rax                 
retq                           retq                              

********************************************************************************


Program received signal SIGILL, Illegal instruction.
0x00007ffff155402e in ?? ()
Missing separate debuginfos, use: dnf debuginfo-install atlas-3.10.2-6.fc23.x86_64 cln-1.3.4-3.fc23.x86_64 gmp-6.0.0-12.fc23.x86_64 iml-1.0.4-3.fc23.x86_64 libgcc-5.3.1-2.fc23.x86_64 libgfortran-5.3.1-2.fc23.x86_64 libgomp-5.3.1-2.fc23.x86_64 libquadmath-5.3.1-2.fc23.x86_64 libstdc++-5.3.1-2.fc23.x86_64
(gdb) disassemble /r 0x00007ffff155402e,+32
Dump of assembler code from 0x7ffff155402e to 0x7ffff155404e:
=> 0x00007ffff155402e:  f2 c4 e2 f8 f2 d7   repnz andn %rdi,%rax,%rdx
   0x00007ffff1554034:  0f 9e c3    setle  %bl
   0x00007ffff1554037:  e9 20 00 00 00  jmpq   0x7ffff155405c
   0x00007ffff155403c:  48 a1 d0 bf fe ff ff 7f 00 00   movabs 0x7ffffffebfd0,%rax
   0x00007ffff1554046:  48 89 c4    mov    %rax,%rsp
   0x00007ffff1554049:  48 c7 c7 04 01 00 00    mov    $0x104,%rdi
End of assembler dump.
```

Similarly faulting instructions:

```
=> 0x00007ffff155402e:  f2 c4 e2 f8 f2 d7   repnz andn %rdi,%rax,%rdx
=> 0x00007ffff1554034:  f2 c4 e2 7b f7 f0   repnz shrx %eax,%eax,%esi
=> 0x00007ffff1554032:  f3 c4 e2 f8 f7 e0   repz bextr %rax,%rax,%rsp
```

Possibly they used to be legal on Haswell but fail on Skylake?

**Comment by bchurchill** [comment]
Unfortunately we haven't done any testing on Skylake yet, so we don't know what's going on.  These do look like illegal instructions (even on haswell), and we don't know how they're being generated.

It would be great if we could debug this, and we want to, but our hands are somewhat tied.  Could you try running "make clean && make debug && make test" and telling us which test(s) fail?

**Comment by bchurchill** [comment]
It's possible we just fixed this in #873.  Would you be willing to confirm?

**Comment by falk-hueffner** [comment]
When #887 is fixed, I'll give it a try!

**Comment by travisdowns** [comment]
I'm hitting this too, but I can't test #873 because it's not merged into the Ubuntu16.04 stream which I need.

**Comment by travisdowns** [comment]
I am running against branch ubuntu16.04, pulled today, which has the fix for #873 , but I am still getting the issue, due to the rep prefix.

**Comment by bchurchill** [comment]
Thank you for the update, we really appreciate it!

I think the underlying issue behind a lot of these is that we're using cpu flags that we haven't tested.  Our lab doesn't even have a skylake machine yet.  So, really the problem we need to fix is the default set of cpu flags.

**Comment by falk-hueffner** [comment]
I re-tested with the current docker image, this issue remains. Four tests fail with "illegal instruction":
```
[==========] 894 tests from 65 test cases ran. (548805 ms total)
[  PASSED  ] 890 tests.
[  FAILED  ] 4 tests, listed below:
[  FAILED  ] IntegrationTest.ExamplesExp
[  FAILED  ] IntegrationTest.SandboxFib
[  FAILED  ] IntegrationTest.SandboxRip
[  FAILED  ] IntegrationTest.SearchNonGoal
```
